apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
